# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo install
      - ls
  pre_build:
    commands:
      - echo pre_build
      - npm install
      - ls
  build:
    commands:
      - echo build
      - npm start &
      - echo started
  post_build:
    commands:
      - echo post_build
      - wget http://localhost:3000 -O index.html
artifacts:
  files:
    - index.html
