# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo install
  pre_build:
    commands:
      - echo pre_build
      - npm install
  build:
    commands:
      - echo build
      - npm start &
      - sleep 1
  post_build:
    commands:
      - echo post_build
      - aws s3 sync --acl public-read public/ s3://morningoogle.com/
      - wget http://localhost:3000 -O index.html
      - aws s3 cp --acl public-read index.html s3://morningoogle.com/
