# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo install
  pre_build:
    commands:
      - echo pre_build
      - npm install
  build:
    commands:
      - echo build
      - npm start &
  post_build:
    commands:
      - echo post_build
      - curl http://localhost:3000 -o public/index.html
      - cat public/index.html
      - aws s3 cp public/index.html s3://morningoogle.com/
artifacts:
  files:
    - '**/*'
  base-directory: public
