# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo install
  pre_build:
    commands:
      - echo pre_build
      - npm install
  build:
    commands:
      - echo build
      - npm start &
  post_build:
    commands:
      - echo post_build
      - wget http://localhost:3000 -O index.html
      - cat index.html
artifacts:
  files:
    - index.html
