---
AWSTemplateFormatVersion: "2010-09-09"
Resources:
  Layer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - nodejs8.10
      Content:
        S3Bucket: morningoogle.com
        S3Key: layer/alexa.zip
      LayerName: alexa
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: alexa
      Handler: index.handler
      Runtime: nodejs8.10
      MemorySize: 512
      Timeout: 60
      Role: !ImportValue LambdaExecutionRoleArn
      Layers:
        - !Ref Layer
      Code:
        ZipFile: |
          var request = require('request');
          var unzipper = require('unzipper');
          var csv2 = require('csv2');

          exports.handler = function(event, context, callback) {
              let res = [];
              request.get('http://s3.amazonaws.com/alexa-static/top-1m.csv.zip')
              .pipe(unzipper.Parse())
                .on('entry', function (entry) {
            	     entry.pipe(csv2()).on('data', function (csv) {
                      res.push({ domain: csv[1], rank: res.length + 1 });
                      if ( res.length > 99 ) {
                          callback(null, res);
                          return;
                      }
                   })
              });
          };
Outputs:
  AlexaFunctionArn:
    Value: !GetAtt LambdaFunction.Arn
    Export:
      Name: AlexaFunctionArn
