---
AWSTemplateFormatVersion: "2010-09-09"
Description: CodeBuild from Codepipeline
Parameters:
  ProjectName:
    Type: String
    Default: morningoogle
Resources:
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/amazonlinux2-x86_64-standard:1.0
        Type: LINUX_CONTAINER
      Name: !Ref ProjectName
      ServiceRole: !ImportValue CodeBuildRoleArn
      Source:
        Type: CODEPIPELINE
